### PR TITLE
[1.18.2] Refactoring transfer materials(item/fluid/energy/gas) to improve server-side performance

### LINKED ISSUE #128: [1.18.2] [SMP] after server restart some pipe not connected to mekanism multiblock
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
after server restart some pipe not connected to mekanism multiblock, - visually they are connected, but nothing transfert.
energy pipe to (insert) induction matrix - every server restart
fluid pipe to (insert) evaporator - every server restart
gas pipe to (insert) industrial turbine - random (~50% chanse)
gas pipe to (insert) fission reactor - random
fluid pipe to (insert) fission reactor - random
gas pipe to (insert) thermo. boiler - random

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Log files**
latest (after server boot) https://gist.github.com/ptk2003/73501d9e058e05a75e241b0c00beeab5
debug (after server boot) https://gist.github.com/ptk2003/50acaa914150e7856c0bb40f47cb75fa

**Versions**
1.18.2-forge-40.1.51
pipez-1.18.2-1.1.5

**Other mods**
Mekanism-1.18.2-10.2.3.463

**Screenshots (Optional)**
Screenshots of the issue.

### LINKED ISSUE #132: [1.18.2] Energy Pipe with Ultimate Upgrade not transferring what it says it can.
**Bug description**
An energy pipe with an ultimate upgrade says that it can transfer 3,275,000 RF / tick. Mekanism's Advanced Solar Generator produces at max 120 RF / tick and can output at max 240 RF / tick. 

However, An energy pipe with an ultimate upgrade cannot transfer all the energy out of the Advanced Solar Generator, meaning that the generator slowly fills up. 

If the ultimate upgrade were working as advertised, then the generator would not have a chance to fill up. It would stay empty. According to the numbers, the pipe should be able to handle at least 13,000 Advanced Solar Generators., but it can't even handle a single one.

On the other end of the pipe is an Ultimate Energy Cube which can handle inputs exceeding 50k RF/t so the input being limited is not the problem.

I had heard that throughput on the pipe is unlimited, is that the case? Is there a limit on how much the pipe can transfer to a device?

**Steps to reproduce the issue**
1. Place down an Advanced Solar Generator, Ultimate Energy Cube, and link them with an Energy Cable set to output on the generator.
2. Add an ultimate upgrade to the output side of the energy pipe.
3. Observe that even though power is being transferred to the Energy Cube, the transfer speed is not sufficient to consume all of what is being produced by the generator; which means that the generator is producing more than what the pipe can handle.

**Expected behavior**
An ultimate upgrade to a pipe should more than be able to handle a single Advanced Solar Generator. 

**Log files**
There are no log files, as this is not a typical crash or error.

**Versions**
- Minecraft version 1.18.2
- Forge version 40.1.68
- Mod version 1.1.5

**Other mods**
- Mekanism Generators version 10.22.5.465

Tested in a world with only Pipez and Mekanism Generators

**Screenshots (Optional)**
image
image

### PR DESCRIPTION
**Pull request by craftingmod**
Kotlin reimplementation and bugfix version of #133.

This PR is for 1.18.2.

# Changes

1. Some of codes are implemented as Kotlin. Now it requires `Kotlin for Forge`.

2. Material(Item/Fluid/Energy/Gas) PipeType is now inherit generic class, `AbsTankPipeType`. Now I can manage all materials code to one.

3. Round-Robin is now running as "equality" mode. Fixes #132 due to round-robin is limited `maxrate` / `connected` whatever connected machine is full of energy.

4. Optimized server tps with various way. Focused on #120 #121. Filtering would be faster with big nbt containers.

5. Extracting sides would be kept even if capability is loss. Neighbor updates triggers dirty pipe whatever blockstate is changed or not. Both fixes #128

# Comment
1. Due to code is written in Kotlin, It would be hard to merge.

2. I've tested and tried to reduce bug but because of Refactoring unexpected bug would be happen.

I'm uploading PR if you could get help fixing various issues 🥲 

# Screenshots

### CODE REVIEW

**Comment by craftingmod** [comment]
Test Build who want to test: [pipez.zip](https://github.com/henkelmax/pipez/files/9388444/pipez.zip)
 
 Require https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files/3925887 !

**Comment by henkelmax** [comment]
I won't accept anything that contains kotlin, sorry.

**Comment by henkelmax** [comment]
I'm also only accepting PRs into master

**Comment by craftingmod** [comment]
> I won't accept anything that contains kotlin, sorry.

No problem~ It's for personal modpack tps optimizing and you could check when fixing bugs.

> I'm also only accepting PRs into master

✅

**Pull request closed without merging**
